### ISSUE TITLE
No resource kind of CStorPoolCluster?

### ISSUE THREAD

**Issue by RottenLeaf24** [openebs/cstor-csi#37]
For the resizer feature,I want to create the CStorPoolCluster.But when create the resource,I get this error:
```
error: unable to recognize "cluster-pool.yaml": no matches for kind "CStorPoolCluster" in version "openebs.io/v1alpha1"
```
The cspc file is :
```
apiVersion: openebs.io/v1alpha1
kind: CStorPoolCluster
metadata:
  name: cstor
  namespace: openebs
  annotations:
    cas.openebs.io/config: |
      - name: Tolerations
        value: |-
          t1:
            effect: NoSchedule
            key: "node-role.kubernetes.io/master"
            operator: Exists
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  pools:
    raidGroups:
    - type: "stripe"
      isWriteCache: false
      isSpare: false
      isReadCache: false
      blockDevices:
      - blockDeviceName: "blockdevice-263ec52bac19b2e65e663bff02224229"
      - blockDeviceName: "blockdevice-75ba6917c814053bc3c3b202cd8dbb10"
      - blockDeviceName: "blockdevice-8a19b43a88d8f294e3ee934367f6630d"
    poolConfig:
      cacheFile: ""
      defaultRaidGroupType: "stripe"
      overProvisioning: false
      compression: "off
```
Wirte this file by learn from https://raw.githubusercontent.com/openebs/csi/master/deploy/cspc.yaml

In addition， the openebs-operator version is 1.2,and the kubernetes version is 1.15.3.
If the openebs still not support CStorPoolCluster yet?
